# Generated by Django 3.0.8 on 2020-09-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='epetition',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='eplastic',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
