# Generated by Django 3.0.8 on 2020-09-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200908_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='edate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
