# Generated by Django 3.0.8 on 2020-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_employee_edate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='edate',
        ),
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
