# Generated by Django 3.0.8 on 2020-09-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200908_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='bolim',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='berth',
            field=models.CharField(choices=[('DR', 'DIREKTOR'), ('BB', 'BO`LIM BOSHLIG`I'), ('BOSH', 'BOSH MUTAXASSIS'), ('YT', 'YETAKCHI MUTAXASSIS'), ('KT', 'KATTA MUTAXASSIS'), ('XT', 'XISOBLASH TEXNIKASI OPERATORI'), ('AL', 'ALOQA OPERATORI'), ('QR', 'QOROVUL'), ('FR', 'FARROSH'), ('PR', 'AMALIYOTCHI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
