# Generated by Django 3.0.8 on 2020-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200908_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='berth',
            field=models.CharField(choices=[('DIREKTOR', 'DIREKTOR'), ('BO`LIM BOSHLIG`I', 'BO`LIM BOSHLIG`I'), ('BOSH MUTAXASSIS', 'BOSH MUTAXASSIS'), ('YETAKCHI MUTAXASSIS', 'YETAKCHI MUTAXASSIS'), ('KATTA MUTAXASSIS', 'KATTA MUTAXASSIS'), ('XISOBLASH TEXNIKASI OPERATORI', 'XISOBLASH TEXNIKASI OPERATORI'), ('ALOQA OPERATORI', 'ALOQA OPERATORI'), ('QOROVUL', 'QOROVUL'), ('FARROSH', 'FARROSH'), ('AMALIYOTCHI', 'AMALIYOTCHI')], max_length=100),
        ),
    ]
