# Generated by Django 3.0.8 on 2020-09-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200911_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markazlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markaz_Nomi', models.CharField(max_length=250)),
                ('telefon', models.CharField(max_length=16)),
                ('manzil', models.CharField(max_length=300)),
                ('ish_Vaqti', models.CharField(max_length=50)),
            ],
        ),
    ]
