# Generated by Django 3.0.8 on 2020-11-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_employee_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(blank=True, max_length=200)),
                ('matn1', models.TextField(blank=True, max_length=3000)),
                ('rasm1', models.ImageField(blank=True, upload_to='yangiliklar/rasmlar/')),
                ('matn2', models.TextField(blank=True, max_length=2000)),
                ('rasm2', models.ImageField(blank=True, upload_to='yangiliklar/rasmlar/')),
                ('rasm3', models.ImageField(blank=True, upload_to='yangiliklar/rasmlar/')),
            ],
        ),
    ]
