# Generated by Django 3.0.8 on 2020-11-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_yangilik'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangilik',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
