# Generated by Django 3.0.8 on 2020-11-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_yangilik_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangilik',
            name='vaqt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
