# Generated by Django 3.0.8 on 2020-11-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_yangilik_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangilik',
            name='vaqt',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
