# Generated by Django 3.0.8 on 2020-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20201126_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha1', models.CharField(blank=True, max_length=300)),
                ('sarlavha2', models.CharField(blank=True, max_length=300)),
                ('matn1', models.TextField(blank=True, max_length=3000)),
                ('matn2', models.TextField(blank=True, max_length=3000)),
                ('matn3', models.TextField(blank=True, max_length=3000)),
            ],
        ),
    ]
