# Generated by Django 3.0.8 on 2020-12-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_biz'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='Telefon',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='biz',
            name='manzil',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='biz',
            name='moljal',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
