# Generated by Django 3.0.8 on 2021-01-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20201205_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galereya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, upload_to='galereya/')),
                ('sarlavha', models.CharField(blank=True, max_length=200)),
                ('matn', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='biz',
            name='Telefon',
        ),
        migrations.AddField(
            model_name='biz',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='biz',
            name='manzil',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='biz',
            name='moljal',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
