# Generated by Django 3.0.8 on 2021-01-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210103_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='galereya',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
