# Generated by Django 3.0.8 on 2021-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20210103_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(blank=True, max_length=200)),
                ('matn', models.TextField(blank=True, max_length=500)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
    ]
