# Generated by Django 3.1 on 2021-01-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_videolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolar',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videolar',
            name='vaqt',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
