# Generated by Django 3.1 on 2021-01-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20210105_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xizmatlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xizmatNomi', models.CharField(max_length=300)),
                ('bajarilishMuddati', models.CharField(blank=True, max_length=20)),
                ('vdo', models.CharField(blank=True, max_length=200)),
                ('yigimMiqdori', models.CharField(blank=True, max_length=100)),
                ('davlatBoji', models.CharField(blank=True, max_length=100)),
                ('qaror', models.CharField(blank=True, max_length=200)),
                ('kerakliHujjatlar', models.TextField(blank=True)),
            ],
        ),
    ]
