# Generated by Django 3.1 on 2021-02-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_xizmatlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='videolar',
            name='matn',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='xizmatlar',
            name='bajarilishMuddati',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='xizmatlar',
            name='vdo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
