# Generated by Django 3.2.4 on 2021-08-19 17:37

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('sana', models.DateField(blank=True, null=True)),
                ('vaqt', models.TimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'Foydali videolar',
            },
        ),
        migrations.AlterModelOptions(
            name='biz',
            options={'verbose_name': 'Biz haqimizda', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Plastik', 'verbose_name_plural': 'Kadastr plastiglari'},
        ),
        migrations.AlterModelOptions(
            name='galereya',
            options={'verbose_name': 'galereya', 'verbose_name_plural': 'Galereya'},
        ),
        migrations.AlterModelOptions(
            name='markazlar',
            options={'verbose_name': 'Markaz', 'verbose_name_plural': 'Markazlar'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Markaz xodimi', 'verbose_name_plural': 'Markaz xodimlari'},
        ),
        migrations.AlterModelOptions(
            name='xizmatlar',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmat turlari'},
        ),
        migrations.AlterModelOptions(
            name='yangilik',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
